"""empty message

Revision ID: 0cb9b2c133c1
Revises: 326669b5e631
Create Date: 2018-04-09 02:40:42.367089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cb9b2c133c1'
down_revision = '326669b5e631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nemi_logging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('target', sa.String(length=300), nullable=True),
    sa.Column('result', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['nemi_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nemi_logging')
    # ### end Alembic commands ###
