"""table file

Revision ID: 59a289a39edf
Revises: c2729464d924
Create Date: 2018-02-05 21:01:31.445232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59a289a39edf'
down_revision = 'c2729464d924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nemi_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_name', sa.String(length=60), nullable=True),
    sa.Column('object_type', sa.String(length=20), nullable=True),
    sa.Column('object_size', sa.Integer(), nullable=True),
    sa.Column('object_uuid', sa.String(length=100), nullable=True),
    sa.Column('is_enable', sa.Boolean(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('bucket_id', sa.Integer(), nullable=True),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.Column('edit_time', sa.DateTime(), nullable=True),
    sa.Column('disable_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bucket_id'], ['nemi_bucket.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['nemi_user.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['nemi_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('nemi_space', sa.Column('root_folder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'nemi_space', 'nemi_file', ['root_folder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nemi_space', type_='foreignkey')
    op.drop_column('nemi_space', 'root_folder_id')
    op.drop_table('nemi_file')
    # ### end Alembic commands ###
