"""empty message

Revision ID: 5a78b473b549
Revises: 654c4bd85dfa
Create Date: 2018-04-08 22:42:19.859932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a78b473b549'
down_revision = '654c4bd85dfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nemi_share_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_name', sa.String(length=60), nullable=True),
    sa.Column('object_type', sa.String(length=20), nullable=True),
    sa.Column('object_size', sa.Integer(), nullable=True),
    sa.Column('object_uuid', sa.String(length=100), nullable=True),
    sa.Column('is_enable', sa.Boolean(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('own_id', sa.Integer(), nullable=True),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['nemi_user.id'], ),
    sa.ForeignKeyConstraint(['original_id'], ['nemi_user.id'], ),
    sa.ForeignKeyConstraint(['own_id'], ['nemi_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nemi_share_file')
    # ### end Alembic commands ###
