"""empty message

Revision ID: 654c4bd85dfa
Revises: cdcd3b3d6a62
Create Date: 2018-04-08 22:06:44.975540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654c4bd85dfa'
down_revision = 'cdcd3b3d6a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nemi_file', sa.Column('open_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nemi_file', 'open_time')
    # ### end Alembic commands ###
