"""Initial migration

Revision ID: c2729464d924
Revises: 
Create Date: 2018-02-05 20:50:08.300715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2729464d924'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nemi_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('username', sa.String(length=40), nullable=True),
    sa.Column('is_enable', sa.Boolean(), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('nickname', sa.String(length=60), nullable=True),
    sa.Column('student_num', sa.String(length=13), nullable=True),
    sa.Column('class_in', sa.String(length=10), nullable=True),
    sa.Column('permission', sa.Integer(), nullable=True),
    sa.Column('is_changed', sa.Boolean(), nullable=True),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.Column('last_login_time', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=60), nullable=True),
    sa.Column('disable_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['nemi_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('nemi_space',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('space_type', sa.String(length=40), nullable=True),
    sa.Column('own_user_id', sa.Integer(), nullable=True),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['own_user_id'], ['nemi_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nemi_bucket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('space_id', sa.Integer(), nullable=True),
    sa.Column('s3_access_key', sa.String(length=100), nullable=True),
    sa.Column('s3_secret_key', sa.String(length=200), nullable=True),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['space_id'], ['nemi_space.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nemi_bucket')
    op.drop_table('nemi_space')
    op.drop_table('nemi_user')
    # ### end Alembic commands ###
